name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Ensure lint/test/typecheck tools are installed
        run: |
          pip install pylint mypy pytest

      - name: Lint with pylint
        run: |
          pylint vscode_sync/main.py tests/test_main.py

      - name: Type check with mypy
        run: |
          mypy vscode_sync/main.py tests/test_main.py

      - name: Run tests with pytest
        run: |
          pytest -v
